FactoryGirl.define do 
	sequence(:email) { |n| "user#{n}@example.com" } #sequence automatically generates sample email addresses
	factory :user do # short for factory :user, class: User do
		email #generated by sequence
    password "1234567890"
    first_name "Peter"
    last_name "Example"
    admin false
	end
	factory :user2, class: User do #fields for user2
		email #generated by sequence
    password "1234567890"
    first_name "Tina"
    last_name "schmidt"
    admin false
	end
	factory :admin, class: User do #fields for admin
		email #generated by sequence
		password "01234567890"
		first_name "Rida"
		last_name "Tahir"
		admin true
	end
end